import type { SandboxTheme } from "./types";

/** VS Code macOS light theme inspired palette */
export const vscodeLight: SandboxTheme = {
  id: "vscode-light",
  name: "VS Code Light",
  kind: "light",
  colors: {
    bgPrimary: "#f5f5f7",
    bgSecondary: "#ffffff",
    bgTertiary: "#e8e8e8",
    fgPrimary: "#1d1d1f",
    fgSecondary: "#6e6e73",
    fgTertiary: "#aeaeb2",
    border: "#d2d2d7",
    accent: "#0071e3",
    scrollbarBg: "transparent",
    scrollbarFg: "rgba(0, 0, 0, 0.15)",
    success: "#34c759",
    error: "#ff3b30",
    titlebarBg: "#e8e8ed",
    titlebarFg: "#1d1d1f",
    sidebarBg: "#1c1c2e",
    sidebarFg: "#c7c7cc",
    sidebarBorder: "#2c2c3e",
    sidebarActive: "rgba(0, 113, 227, 0.2)",
    panelBg: "#ffffff",
  },
  terminal: {
    background: "#1e1e2e",
    foreground: "#cdd6f4",
    cursor: "#f5e0dc",
    cursorAccent: "#1e1e2e",
    selectionBackground: "rgba(137, 180, 250, 0.3)",
    selectionForeground: "#cdd6f4",
    black: "#45475a",
    red: "#f38ba8",
    green: "#a6e3a1",
    yellow: "#f9e2af",
    blue: "#89b4fa",
    magenta: "#f5c2e7",
    cyan: "#94e2d5",
    white: "#bac2de",
    brightBlack: "#585b70",
    brightRed: "#f38ba8",
    brightGreen: "#a6e3a1",
    brightYellow: "#f9e2af",
    brightBlue: "#89b4fa",
    brightMagenta: "#f5c2e7",
    brightCyan: "#94e2d5",
    brightWhite: "#a6adc8",
  },
};
